### ISSUE TITLE
Incomplete view of table on the RiskAnalysis tab

### ISSUE THREAD

**Issue by jtay50** [jmirch/RiskAnalysisExtension#1]
Hi there, 

Absolutely love this extension! Only problem I'm having is that in games with 7+ players (excluding the neutral) the table extends lower than the interface and I can't see the stats for the bottom few players. Please see below a snip to show you what I mean. As you can see, the stats for 'Tyler1' and 'hoandco' are obscured from view. Is this something that can be amended? 

Thanks!

![image](https://user-images.githubusercontent.com/79453262/108705213-ebb8ae00-7504-11eb-83e1-108032850820.png)

**Comment by jmirch** [comment]
Hey jtay50,

Mind sending me the game number for this? Ill need a big game I can test
the fix with.

Thanks,
jmirch

**Comment by jmirch** [comment]
Actually nvm, I found the game. The fix will be in the next release of the
extension. You should automatically get the new version shortly after its
released

**Comment by jtay50** [comment]
Amazing thanks so much!

**Comment by jtay50** [comment]
Thank you for fixing! Works perfectly now

**Comment by jmirch** [comment]
Awesome! Good to know
